// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// group_demean_formula_cpp
NumericVector group_demean_formula_cpp(NumericVector Z, IntegerVector unit_group, IntegerVector time_group, IntegerVector covar_group);
RcppExport SEXP _HDpcluster_group_demean_formula_cpp(SEXP ZSEXP, SEXP unit_groupSEXP, SEXP time_groupSEXP, SEXP covar_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit_group(unit_groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_group(time_groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type covar_group(covar_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(group_demean_formula_cpp(Z, unit_group, time_group, covar_group));
    return rcpp_result_gen;
END_RCPP
}
// pseudo_dist_unit
NumericMatrix pseudo_dist_unit(NumericVector z);
RcppExport SEXP _HDpcluster_pseudo_dist_unit(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudo_dist_unit(z));
    return rcpp_result_gen;
END_RCPP
}
// pseudo_dist_time
NumericMatrix pseudo_dist_time(NumericVector z);
RcppExport SEXP _HDpcluster_pseudo_dist_time(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudo_dist_time(z));
    return rcpp_result_gen;
END_RCPP
}
// pseudo_dist_covariate
NumericMatrix pseudo_dist_covariate(NumericVector z);
RcppExport SEXP _HDpcluster_pseudo_dist_covariate(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudo_dist_covariate(z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HDpcluster_group_demean_formula_cpp", (DL_FUNC) &_HDpcluster_group_demean_formula_cpp, 4},
    {"_HDpcluster_pseudo_dist_unit", (DL_FUNC) &_HDpcluster_pseudo_dist_unit, 1},
    {"_HDpcluster_pseudo_dist_time", (DL_FUNC) &_HDpcluster_pseudo_dist_time, 1},
    {"_HDpcluster_pseudo_dist_covariate", (DL_FUNC) &_HDpcluster_pseudo_dist_covariate, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_HDpcluster(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
