# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

group_demean_formula_cpp <- function(Z, unit_group, time_group, covar_group) {
    .Call('_HDpcluster_group_demean_formula_cpp', PACKAGE = 'HDpcluster', Z, unit_group, time_group, covar_group)
}

pseudo_dist_unit <- function(z) {
    .Call('_HDpcluster_pseudo_dist_unit', PACKAGE = 'HDpcluster', z)
}

pseudo_dist_time <- function(z) {
    .Call('_HDpcluster_pseudo_dist_time', PACKAGE = 'HDpcluster', z)
}

pseudo_dist_covariate <- function(z) {
    .Call('_HDpcluster_pseudo_dist_covariate', PACKAGE = 'HDpcluster', z)
}

